use_frameworks!

platform :ios, '9.0'

target 'WXNSDK6_Example' do
  pod 'WXNSDK6', :path => '../'

  target 'WXNSDK6_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
